### PR TITLE
Fixed path issue and misc cleanup in update-dependencies

### LINKED ISSUE #332: Maestro Executor fails with 'Can't find `.version` information in installer.'
https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=829537&_a=summary
and
https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=829543&_a=summary

### PR DESCRIPTION
**Pull request by MichaelSimons**
Fixes #332

### CODE REVIEW

File: update-dependencies/CliDependencyHelper.cs [hunk 1]
```diff
@@ -39,7 +39,7 @@ private static string GetCommitHash(string cliVersion)
         {
             using (ZipArchive archive = DownloadCliInstaller(cliVersion).Result)
             {
-                ZipArchiveEntry versionTxtEntry = archive.GetEntry($"sdk/{cliVersion}/.version");
+                ZipArchiveEntry versionTxtEntry = archive.GetEntry($"sdk\\{cliVersion}\\.version");
```
Comment (dagood) [inline update-dependencies/CliDependencyHelper.cs]: Interesting... do you know why this changed?

Comment (MichaelSimons) [inline update-dependencies/CliDependencyHelper.cs]: I looked briefly and didn't see a change that looked like it caused this.  The change makes sense however since this is a windows zip.
